import { PAGES_HANDLES } from '@/components/pages/handles';

export const PAGES_LIMIT_DEFAULT = -1;

export const PAGES_LIMIT_HANDLES = {
    [PAGES_HANDLES.CUSTOM_PAGE]: process.env.NEXT_PUBLIC_PRERENDER_LIMIT_PAGES
        ? parseInt(process.env.NEXT_PUBLIC_PRERENDER_LIMIT_PAGES)
        : PAGES_LIMIT_DEFAULT,
    [PAGES_HANDLES.PRODUCT_DETAIL]: process.env.NEXT_PUBLIC_PRERENDER_LIMIT_PRODUCTS
        ? parseInt(process.env.NEXT_PUBLIC_PRERENDER_LIMIT_PRODUCTS)
        : PAGES_LIMIT_DEFAULT,
    [PAGES_HANDLES.PRODUCT_LISTING]: process.env.NEXT_PUBLIC_PRERENDER_LIMIT_CATEGORIES
        ? parseInt(process.env.NEXT_PUBLIC_PRERENDER_LIMIT_CATEGORIES)
        : PAGES_LIMIT_DEFAULT,
} as const;
