/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialMedia".
 */
export type SocialMedia =
    | {
          icon?: Icon;
          link?: Link;
          id?: string | null;
      }[]
    | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
    | 'Pacific/Midway'
    | 'Pacific/Niue'
    | 'Pacific/Honolulu'
    | 'Pacific/Rarotonga'
    | 'America/Anchorage'
    | 'Pacific/Gambier'
    | 'America/Los_Angeles'
    | 'America/Tijuana'
    | 'America/Denver'
    | 'America/Phoenix'
    | 'America/Chicago'
    | 'America/Guatemala'
    | 'America/New_York'
    | 'America/Bogota'
    | 'America/Caracas'
    | 'America/Santiago'
    | 'America/Buenos_Aires'
    | 'America/Sao_Paulo'
    | 'Atlantic/South_Georgia'
    | 'Atlantic/Azores'
    | 'Atlantic/Cape_Verde'
    | 'Europe/London'
    | 'Europe/Berlin'
    | 'Africa/Lagos'
    | 'Europe/Athens'
    | 'Africa/Cairo'
    | 'Europe/Moscow'
    | 'Asia/Riyadh'
    | 'Asia/Dubai'
    | 'Asia/Baku'
    | 'Asia/Karachi'
    | 'Asia/Tashkent'
    | 'Asia/Calcutta'
    | 'Asia/Dhaka'
    | 'Asia/Almaty'
    | 'Asia/Jakarta'
    | 'Asia/Bangkok'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Tokyo'
    | 'Asia/Seoul'
    | 'Australia/Brisbane'
    | 'Australia/Sydney'
    | 'Pacific/Guam'
    | 'Pacific/Noumea'
    | 'Pacific/Auckland'
    | 'Pacific/Fiji';

export interface Config {
    auth: {
        tokens: TokenAuthOperations;
        users: UserAuthOperations;
    };
    blocks: {};
    collections: {
        addons: Addon;
        categories: Category;
        mediaAddon: MediaAddon;
        mediaGallery: MediaGallery;
        mediaGlobal: MediaGlobal;
        mediaProduct: MediaProduct;
        pages: Page;
        products: Product;
        tags: Tag;
        testimonials: Testimonial;
        tokens: Token;
        users: User;
        'payload-locked-documents': PayloadLockedDocument;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        addons: AddonsSelect<false> | AddonsSelect<true>;
        categories: CategoriesSelect<false> | CategoriesSelect<true>;
        mediaAddon: MediaAddonSelect<false> | MediaAddonSelect<true>;
        mediaGallery: MediaGallerySelect<false> | MediaGallerySelect<true>;
        mediaGlobal: MediaGlobalSelect<false> | MediaGlobalSelect<true>;
        mediaProduct: MediaProductSelect<false> | MediaProductSelect<true>;
        pages: PagesSelect<false> | PagesSelect<true>;
        products: ProductsSelect<false> | ProductsSelect<true>;
        tags: TagsSelect<false> | TagsSelect<true>;
        testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
        tokens: TokensSelect<false> | TokensSelect<true>;
        users: UsersSelect<false> | UsersSelect<true>;
        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: number;
    };
    globals: {
        navigation: Navigation;
        homepage: Homepage;
        footer: Footer;
    };
    globalsSelect: {
        navigation: NavigationSelect<false> | NavigationSelect<true>;
        homepage: HomepageSelect<false> | HomepageSelect<true>;
        footer: FooterSelect<false> | FooterSelect<true>;
    };
    locale: null;
    user:
        | (Token & {
              collection: 'tokens';
          })
        | (User & {
              collection: 'users';
          });
    jobs: {
        tasks: unknown;
        workflows: unknown;
    };
}
export interface TokenAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons".
 */
export interface Addon {
    id: number;
    typeHandle?: string | null;
    entryStatus?: ('disabled' | 'live') | null;
    title: string;
    slug?: string | null;
    url?: string | null;
    uri?: string | null;
    thumbnail: number | MediaAddon;
    prices: {
        price: Price;
        id?: string | null;
    }[];
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaAddon".
 */
export interface MediaAddon {
    id: number;
    alt: string;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        assets400x400?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Price".
 */
export interface Price {
    normalPrice: number;
    salePrice?: number | null;
    note?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
    id: number;
    typeHandle?: string | null;
    entryStatus?: ('disabled' | 'live') | null;
    title: string;
    slug?: string | null;
    url?: string | null;
    uri?: string | null;
    description?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    meta?: Meta;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?:
        | ({
              relationTo: 'mediaAddon';
              value: number | MediaAddon;
          } | null)
        | ({
              relationTo: 'mediaGlobal';
              value: number | MediaGlobal;
          } | null)
        | ({
              relationTo: 'mediaProduct';
              value: number | MediaProduct;
          } | null)
        | ({
              relationTo: 'mediaGallery';
              value: number | MediaGallery;
          } | null);
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGlobal".
 */
export interface MediaGlobal {
    id: number;
    alt: string;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        bannerDesktop?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerTablet?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        storyMediaDesktop?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        storyMediaMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        mediaDividerTablet?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        mediaDividerMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaProduct".
 */
export interface MediaProduct {
    id: number;
    alt: string;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        bannerDesktop?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerTablet?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productDetailBanner?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productDetailSticky?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productDetailMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productMarquee?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productMarqueeMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productListingThumbnail?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productListingThumbnailMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGallery".
 */
export interface MediaGallery {
    id: number;
    alt: string;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        collage1x1?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage4x3?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage3x4?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage3x2?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage2x3?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
    id: number;
    typeHandle?: string | null;
    entryStatus?: ('disabled' | 'live') | null;
    title: string;
    slug?: string | null;
    url?: string | null;
    uri?: string | null;
    contentBlocks?:
        | (ContentBlockGallery | ContentBlockHeading | ContentBlockRelatedProducts | ContentBlockCallout)[]
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockGallery".
 */
export interface ContentBlockGallery {
    media?: (number | MediaGallery)[] | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbSpacing".
 */
export interface CbSpacing {
    marginTop?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
    marginBottom?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockHeading".
 */
export interface ContentBlockHeading {
    title?: string | null;
    headingLevel?: ('1' | '2' | '3' | '4' | '5') | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockRelatedProducts".
 */
export interface ContentBlockRelatedProducts {
    title?: string | null;
    products?: (number | Product)[] | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'relatedProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
    id: number;
    typeHandle?: string | null;
    entryStatus?: ('disabled' | 'live') | null;
    title: string;
    slug?: string | null;
    url?: string | null;
    uri?: string | null;
    thumbnail?: (number | null) | MediaProduct;
    thumbnailHover?: (number | null) | MediaProduct;
    marquee?: (number | MediaProduct)[] | null;
    bannerTitle?: string | null;
    description: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    category: number | Category;
    flavour: Flavour;
    prices: {
        price: Price;
        id?: string | null;
    }[];
    addons?: (number | Addon)[] | null;
    meta?: Meta;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Flavour".
 */
export interface Flavour {
    freshCreamy: '_0' | '_10' | '_20' | '_30' | '_40' | '_50' | '_60' | '_70' | '_80' | '_90' | '_100';
    custardySpongy: '_0' | '_10' | '_20' | '_30' | '_40' | '_50' | '_60' | '_70' | '_80' | '_90' | '_100';
    tangySweet: '_0' | '_10' | '_20' | '_30' | '_40' | '_50' | '_60' | '_70' | '_80' | '_90' | '_100';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockCallout".
 */
export interface ContentBlockCallout {
    title?: string | null;
    link?: Link;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link".
 */
export interface Link {
    source?: ('products' | 'categories' | 'pages' | 'mail' | 'custom') | null;
    product?: (number | null) | Product;
    page?: (number | null) | Page;
    category?: (number | null) | Category;
    custom?: string | null;
    mail?: string | null;
    target?: boolean | null;
    label?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
    id: number;
    typeHandle?: string | null;
    entryStatus?: ('disabled' | 'live') | null;
    title: string;
    slug?: string | null;
    url?: string | null;
    uri?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
    id: number;
    typeHandle?: string | null;
    entryStatus?: ('disabled' | 'live') | null;
    title: string;
    slug?: string | null;
    url?: string | null;
    uri?: string | null;
    author: string;
    testimonial: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokens".
 */
export interface Token {
    id: number;
    title: string;
    updatedAt: string;
    createdAt: string;
    enableAPIKey?: boolean | null;
    apiKey?: string | null;
    apiKeyIndex?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: number;
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    sessions?:
        | {
              id: string;
              createdAt?: string | null;
              expiresAt: string;
          }[]
        | null;
    password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: number;
    document?:
        | ({
              relationTo: 'addons';
              value: number | Addon;
          } | null)
        | ({
              relationTo: 'categories';
              value: number | Category;
          } | null)
        | ({
              relationTo: 'mediaAddon';
              value: number | MediaAddon;
          } | null)
        | ({
              relationTo: 'mediaGallery';
              value: number | MediaGallery;
          } | null)
        | ({
              relationTo: 'mediaGlobal';
              value: number | MediaGlobal;
          } | null)
        | ({
              relationTo: 'mediaProduct';
              value: number | MediaProduct;
          } | null)
        | ({
              relationTo: 'pages';
              value: number | Page;
          } | null)
        | ({
              relationTo: 'products';
              value: number | Product;
          } | null)
        | ({
              relationTo: 'tags';
              value: number | Tag;
          } | null)
        | ({
              relationTo: 'testimonials';
              value: number | Testimonial;
          } | null)
        | ({
              relationTo: 'tokens';
              value: number | Token;
          } | null)
        | ({
              relationTo: 'users';
              value: number | User;
          } | null);
    globalSlug?: string | null;
    user:
        | {
              relationTo: 'tokens';
              value: number | Token;
          }
        | {
              relationTo: 'users';
              value: number | User;
          };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user:
        | {
              relationTo: 'tokens';
              value: number | Token;
          }
        | {
              relationTo: 'users';
              value: number | User;
          };
    key?: string | null;
    value?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons_select".
 */
export interface AddonsSelect<T extends boolean = true> {
    typeHandle?: T;
    entryStatus?: T;
    title?: T;
    slug?: T;
    url?: T;
    uri?: T;
    thumbnail?: T;
    prices?:
        | T
        | {
              price?: T | PriceSelect<T>;
              id?: T;
          };
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Price_select".
 */
export interface PriceSelect<T extends boolean = true> {
    normalPrice?: T;
    salePrice?: T;
    note?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
    typeHandle?: T;
    entryStatus?: T;
    title?: T;
    slug?: T;
    url?: T;
    uri?: T;
    description?: T;
    meta?: T | MetaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Meta_select".
 */
export interface MetaSelect<T extends boolean = true> {
    title?: T;
    description?: T;
    image?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaAddon_select".
 */
export interface MediaAddonSelect<T extends boolean = true> {
    alt?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              assets400x400?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGallery_select".
 */
export interface MediaGallerySelect<T extends boolean = true> {
    alt?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              collage1x1?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage4x3?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage3x4?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage3x2?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage2x3?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGlobal_select".
 */
export interface MediaGlobalSelect<T extends boolean = true> {
    alt?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              bannerDesktop?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerTablet?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              storyMediaDesktop?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              storyMediaMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              mediaDividerTablet?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              mediaDividerMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaProduct_select".
 */
export interface MediaProductSelect<T extends boolean = true> {
    alt?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              bannerDesktop?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerTablet?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productDetailBanner?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productDetailSticky?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productDetailMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productMarquee?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productMarqueeMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productListingThumbnail?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productListingThumbnailMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
    typeHandle?: T;
    entryStatus?: T;
    title?: T;
    slug?: T;
    url?: T;
    uri?: T;
    contentBlocks?:
        | T
        | {
              gallery?: T | ContentBlockGallerySelect<T>;
              heading?: T | ContentBlockHeadingSelect<T>;
              relatedProducts?: T | ContentBlockRelatedProductsSelect<T>;
              callout?: T | ContentBlockCalloutSelect<T>;
          };
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockGallery_select".
 */
export interface ContentBlockGallerySelect<T extends boolean = true> {
    media?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbSpacing_select".
 */
export interface CbSpacingSelect<T extends boolean = true> {
    marginTop?: T;
    marginBottom?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockHeading_select".
 */
export interface ContentBlockHeadingSelect<T extends boolean = true> {
    title?: T;
    headingLevel?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockRelatedProducts_select".
 */
export interface ContentBlockRelatedProductsSelect<T extends boolean = true> {
    title?: T;
    products?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlockCallout_select".
 */
export interface ContentBlockCalloutSelect<T extends boolean = true> {
    title?: T;
    link?: T | LinkSelect<T>;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link_select".
 */
export interface LinkSelect<T extends boolean = true> {
    source?: T;
    product?: T;
    page?: T;
    category?: T;
    custom?: T;
    mail?: T;
    target?: T;
    label?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
    typeHandle?: T;
    entryStatus?: T;
    title?: T;
    slug?: T;
    url?: T;
    uri?: T;
    thumbnail?: T;
    thumbnailHover?: T;
    marquee?: T;
    bannerTitle?: T;
    description?: T;
    category?: T;
    flavour?: T | FlavourSelect<T>;
    prices?:
        | T
        | {
              price?: T | PriceSelect<T>;
              id?: T;
          };
    addons?: T;
    meta?: T | MetaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Flavour_select".
 */
export interface FlavourSelect<T extends boolean = true> {
    freshCreamy?: T;
    custardySpongy?: T;
    tangySweet?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
    typeHandle?: T;
    entryStatus?: T;
    title?: T;
    slug?: T;
    url?: T;
    uri?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
    typeHandle?: T;
    entryStatus?: T;
    title?: T;
    slug?: T;
    url?: T;
    uri?: T;
    author?: T;
    testimonial?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokens_select".
 */
export interface TokensSelect<T extends boolean = true> {
    title?: T;
    updatedAt?: T;
    createdAt?: T;
    enableAPIKey?: T;
    apiKey?: T;
    apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    updatedAt?: T;
    createdAt?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
    sessions?:
        | T
        | {
              id?: T;
              createdAt?: T;
              expiresAt?: T;
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
    id: number;
    navigations?:
        | {
              entryStatus?: ('disabled' | 'live') | null;
              link?: Link;
              id?: string | null;
          }[]
        | null;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
    id: number;
    typeHandle?: string | null;
    entryStatus?: ('disabled' | 'live') | null;
    title: string;
    slug?: string | null;
    url?: string | null;
    uri?: string | null;
    bannerMedia?:
        | {
              source?: ('products' | 'custom') | null;
              entryStatus?: ('disabled' | 'live') | null;
              tag?: (number | null) | Tag;
              textAlign?: ('left' | 'right') | null;
              bannerOverlay?: ('0' | '1' | '2' | '3' | '4' | '5') | null;
              media?: (number | null) | MediaGlobal;
              title?: string | null;
              description?: {
                  root: {
                      type: string;
                      children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                  };
                  [k: string]: unknown;
              } | null;
              link?: Link;
              product?: (number | null) | Product;
              productTarget?: boolean | null;
              id?: string | null;
          }[]
        | null;
    highlights?:
        | {
              tag: number | Tag;
              products: (number | Product)[];
              id?: string | null;
          }[]
        | null;
    storyMediaMain?: (number | null) | MediaGlobal;
    storyMediaSecondary?: (number | null) | MediaGlobal;
    storyDescription?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    testimonials?: (number | Testimonial)[] | null;
    imageDividerMedia?: (number | null) | MediaGlobal;
    orderDescription?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    orderSteps?:
        | {
              title?: string | null;
              description?: {
                  root: {
                      type: string;
                      children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                  };
                  [k: string]: unknown;
              } | null;
              id?: string | null;
          }[]
        | null;
    meta?: Meta;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
    id: number;
    address?: string | null;
    businessHours?: string | null;
    socialMedia?: SocialMedia;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Icon".
 */
export interface Icon {
    source?: 'reactIcon' | null;
    reactIcon?: ('CiInstagram' | 'CiMail') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
    navigations?:
        | T
        | {
              entryStatus?: T;
              link?: T | LinkSelect<T>;
              id?: T;
          };
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
    typeHandle?: T;
    entryStatus?: T;
    title?: T;
    slug?: T;
    url?: T;
    uri?: T;
    bannerMedia?:
        | T
        | {
              source?: T;
              entryStatus?: T;
              tag?: T;
              textAlign?: T;
              bannerOverlay?: T;
              media?: T;
              title?: T;
              description?: T;
              link?: T | LinkSelect<T>;
              product?: T;
              productTarget?: T;
              id?: T;
          };
    highlights?:
        | T
        | {
              tag?: T;
              products?: T;
              id?: T;
          };
    storyMediaMain?: T;
    storyMediaSecondary?: T;
    storyDescription?: T;
    testimonials?: T;
    imageDividerMedia?: T;
    orderDescription?: T;
    orderSteps?:
        | T
        | {
              title?: T;
              description?: T;
              id?: T;
          };
    meta?: T | MetaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
    address?: T;
    businessHours?: T;
    socialMedia?: T | SocialMediaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialMedia_select".
 */
export interface SocialMediaSelect<T extends boolean = true> {
    icon?: T | IconSelect<T>;
    link?: T | LinkSelect<T>;
    id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Icon_select".
 */
export interface IconSelect<T extends boolean = true> {
    source?: T;
    reactIcon?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}

declare module 'payload' {
    export interface GeneratedTypes extends Config {}
}
