/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialMedia".
 */
export type SocialMedia =
    | {
          icon?: Icon;
          link?: Link;
          id?: string | null;
      }[]
    | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
    | 'Pacific/Midway'
    | 'Pacific/Niue'
    | 'Pacific/Honolulu'
    | 'Pacific/Rarotonga'
    | 'America/Anchorage'
    | 'Pacific/Gambier'
    | 'America/Los_Angeles'
    | 'America/Tijuana'
    | 'America/Denver'
    | 'America/Phoenix'
    | 'America/Chicago'
    | 'America/Guatemala'
    | 'America/New_York'
    | 'America/Bogota'
    | 'America/Caracas'
    | 'America/Santiago'
    | 'America/Buenos_Aires'
    | 'America/Sao_Paulo'
    | 'Atlantic/South_Georgia'
    | 'Atlantic/Azores'
    | 'Atlantic/Cape_Verde'
    | 'Europe/London'
    | 'Europe/Berlin'
    | 'Africa/Lagos'
    | 'Europe/Athens'
    | 'Africa/Cairo'
    | 'Europe/Moscow'
    | 'Asia/Riyadh'
    | 'Asia/Dubai'
    | 'Asia/Baku'
    | 'Asia/Karachi'
    | 'Asia/Tashkent'
    | 'Asia/Calcutta'
    | 'Asia/Dhaka'
    | 'Asia/Almaty'
    | 'Asia/Jakarta'
    | 'Asia/Bangkok'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Tokyo'
    | 'Asia/Seoul'
    | 'Australia/Brisbane'
    | 'Australia/Sydney'
    | 'Pacific/Guam'
    | 'Pacific/Noumea'
    | 'Pacific/Auckland'
    | 'Pacific/Fiji';

export interface Config {
    auth: {
        tokens: TokenAuthOperations;
        users: UserAuthOperations;
    };
    blocks: {};
    collections: {
        mediaAddons: MediaAddon;
        mediaDualPanels: MediaDualPanel;
        mediaGalleries: MediaGallery;
        mediaGlobals: MediaGlobal;
        mediaMarquees: MediaMarquee;
        mediaProducts: MediaProduct;
        testimonials: Testimonial;
        addons: Addon;
        categories: Category;
        tags: Tag;
        pages: Page;
        products: Product;
        tokens: Token;
        users: User;
        'payload-kv': PayloadKv;
        'payload-locked-documents': PayloadLockedDocument;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
    };
    collectionsJoins: {};
    collectionsSelect: {
        mediaAddons: MediaAddonsSelect<false> | MediaAddonsSelect<true>;
        mediaDualPanels: MediaDualPanelsSelect<false> | MediaDualPanelsSelect<true>;
        mediaGalleries: MediaGalleriesSelect<false> | MediaGalleriesSelect<true>;
        mediaGlobals: MediaGlobalsSelect<false> | MediaGlobalsSelect<true>;
        mediaMarquees: MediaMarqueesSelect<false> | MediaMarqueesSelect<true>;
        mediaProducts: MediaProductsSelect<false> | MediaProductsSelect<true>;
        testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
        addons: AddonsSelect<false> | AddonsSelect<true>;
        categories: CategoriesSelect<false> | CategoriesSelect<true>;
        tags: TagsSelect<false> | TagsSelect<true>;
        pages: PagesSelect<false> | PagesSelect<true>;
        products: ProductsSelect<false> | ProductsSelect<true>;
        tokens: TokensSelect<false> | TokensSelect<true>;
        users: UsersSelect<false> | UsersSelect<true>;
        'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
        'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
        'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
        'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    };
    db: {
        defaultIDType: number;
    };
    fallbackLocale: null;
    globals: {
        navigation: Navigation;
        homepage: Homepage;
        footer: Footer;
    };
    globalsSelect: {
        navigation: NavigationSelect<false> | NavigationSelect<true>;
        homepage: HomepageSelect<false> | HomepageSelect<true>;
        footer: FooterSelect<false> | FooterSelect<true>;
    };
    locale: null;
    widgets: {
        collections: CollectionsWidget;
    };
    user: Token | User;
    jobs: {
        tasks: unknown;
        workflows: unknown;
    };
}
export interface TokenAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
export interface UserAuthOperations {
    forgotPassword: {
        email: string;
        password: string;
    };
    login: {
        email: string;
        password: string;
    };
    registerFirstUser: {
        email: string;
        password: string;
    };
    unlock: {
        email: string;
        password: string;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaAddons".
 */
export interface MediaAddon {
    id: number;
    alt: string;
    mobileAssets?: (number | null) | MediaAddon;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        assets400x400?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaDualPanels".
 */
export interface MediaDualPanel {
    id: number;
    alt: string;
    mobileAssets?: (number | null) | MediaDualPanel;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        media950x594?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        media950x975?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        mediaSquare?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        media4x3?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGalleries".
 */
export interface MediaGallery {
    id: number;
    alt: string;
    mobileAssets?: (number | null) | MediaGallery;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        collage1x1?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage4x3?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage3x4?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage3x2?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        collage2x3?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGlobals".
 */
export interface MediaGlobal {
    id: number;
    alt: string;
    mobileAssets?: (number | null) | MediaGlobal;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        bannerDesktop?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerTablet?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        storyMediaDesktop?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        storyMediaMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        mediaDividerTablet?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        mediaDividerMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaMarquees".
 */
export interface MediaMarquee {
    id: number;
    alt: string;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        marquee?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        marqueeMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaProducts".
 */
export interface MediaProduct {
    id: number;
    alt: string;
    portraitAssets?: (number | null) | MediaProduct;
    prefix?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    thumbnailURL?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        bannerDesktop?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerTablet?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        bannerMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productPopupBanner?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productDetailBanner?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productDetailSticky?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productDetailMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productMarquee?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productMarqueeMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productListingThumbnail?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        productListingThumbnailMobile?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
    id: number;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    url?: string | null;
    uri?: string | null;
    author: string;
    testimonial: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons".
 */
export interface Addon {
    id: number;
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    url?: string | null;
    uri?: string | null;
    thumbnail: number | MediaAddon;
    hasNote?: boolean | null;
    note?: string | null;
    prices: {
        price: Price;
        id?: string | null;
    }[];
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Price".
 */
export interface Price {
    normalPrice: number;
    salePrice?: number | null;
    isFree?: boolean | null;
    note?: string | null;
    additionalInfo?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
    id: number;
    typeHandle: 'sectionTaxonomiesCategory';
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
    id: number;
    typeHandle: 'sectionTaxonomiesTag';
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    /**
     * This will only shown on badge component
     */
    badgeTitle?: string | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
    id: number;
    typeHandle: 'sectionStaticPage' | 'sectionProductListingIndex';
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    url?: string | null;
    uri?: string | null;
    contentBlocks?: ContentBlocks;
    headerTitle?: string | null;
    headerDescription?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    headerBackground?: (number | null) | MediaProduct;
    category?: (number | null) | Category;
    meta?: Meta;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlocks".
 */
export interface ContentBlocks {
    blocks?: (CbCallout | CbDualPanel | CbGallery | CbHeading | CbMarquee | CbRelatedProducts)[] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbCallout".
 */
export interface CbCallout {
    title?: string | null;
    link?: Link;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link".
 */
export interface Link {
    source?: ('custom' | 'mail' | 'products' | 'pages' | 'whatsapp') | null;
    product?: (number | null) | Product;
    page?: (number | null) | Page;
    custom?: string | null;
    mail?: string | null;
    whatsappNumber?: string | null;
    target?: boolean | null;
    whatsappMessage?: string | null;
    label?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
    id: number;
    _order?: string | null;
    typeHandle: 'sectionProductIndex';
    slug: string;
    entryStatus: 'disabled' | 'live';
    availability: 'available' | 'unavailable';
    unavailableLabel?: (number | null) | Tag;
    title: string;
    url?: string | null;
    uri?: string | null;
    thumbnail?: (number | null) | MediaProduct;
    thumbnailHover?: (number | null) | MediaProduct;
    marquee?: (number | MediaProduct)[] | null;
    bannerTitle?: string | null;
    description: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    };
    category: number | Category;
    /**
     * Badge will only shown on product listing page
     */
    badge?: (number | null) | Tag;
    quantity?: number | null;
    flavour?: Flavour;
    prices: {
        price: Price;
        id?: string | null;
    }[];
    addons?: (number | Addon)[] | null;
    meta?: Meta;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Flavour".
 */
export interface Flavour {
    showFlavour?: boolean | null;
    freshCreamy?: ('_0' | '_10' | '_20' | '_30' | '_40' | '_50' | '_60' | '_70' | '_80' | '_90' | '_100') | null;
    custardySpongy?: ('_0' | '_10' | '_20' | '_30' | '_40' | '_50' | '_60' | '_70' | '_80' | '_90' | '_100') | null;
    tangySweet?: ('_0' | '_10' | '_20' | '_30' | '_40' | '_50' | '_60' | '_70' | '_80' | '_90' | '_100') | null;
    fruityNutty?: ('_0' | '_10' | '_20' | '_30' | '_40' | '_50' | '_60' | '_70' | '_80' | '_90' | '_100') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Meta".
 */
export interface Meta {
    title?: string | null;
    description?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbSpacing".
 */
export interface CbSpacing {
    marginTop?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
    marginBottom?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbDualPanel".
 */
export interface CbDualPanel {
    contents?:
        | {
              type: 'text' | 'media';
              description?: {
                  root: {
                      type: string;
                      children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                  };
                  [k: string]: unknown;
              } | null;
              media?: (number | null) | MediaDualPanel;
              id?: string | null;
          }[]
        | null;
    link?: Link;
    layout?: ('_2_3' | '_3_2' | '_1_1') | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'dualPanel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbGallery".
 */
export interface CbGallery {
    media?: (number | MediaGallery)[] | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbHeading".
 */
export interface CbHeading {
    title?: string | null;
    description?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbMarquee".
 */
export interface CbMarquee {
    media?: (number | MediaMarquee)[] | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbRelatedProducts".
 */
export interface CbRelatedProducts {
    title?: string | null;
    products?: (number | Product)[] | null;
    cbSpacing?: CbSpacing;
    id?: string | null;
    blockName?: string | null;
    blockType: 'relatedProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokens".
 */
export interface Token {
    id: number;
    title: string;
    updatedAt: string;
    createdAt: string;
    enableAPIKey?: boolean | null;
    apiKey?: string | null;
    apiKeyIndex?: string | null;
    collection: 'tokens';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: number;
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    sessions?:
        | {
              id: string;
              createdAt?: string | null;
              expiresAt: string;
          }[]
        | null;
    password?: string | null;
    collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
    id: number;
    key: string;
    data:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
    id: number;
    document?:
        | ({
              relationTo: 'mediaAddons';
              value: number | MediaAddon;
          } | null)
        | ({
              relationTo: 'mediaDualPanels';
              value: number | MediaDualPanel;
          } | null)
        | ({
              relationTo: 'mediaGalleries';
              value: number | MediaGallery;
          } | null)
        | ({
              relationTo: 'mediaGlobals';
              value: number | MediaGlobal;
          } | null)
        | ({
              relationTo: 'mediaMarquees';
              value: number | MediaMarquee;
          } | null)
        | ({
              relationTo: 'mediaProducts';
              value: number | MediaProduct;
          } | null)
        | ({
              relationTo: 'testimonials';
              value: number | Testimonial;
          } | null)
        | ({
              relationTo: 'addons';
              value: number | Addon;
          } | null)
        | ({
              relationTo: 'categories';
              value: number | Category;
          } | null)
        | ({
              relationTo: 'tags';
              value: number | Tag;
          } | null)
        | ({
              relationTo: 'pages';
              value: number | Page;
          } | null)
        | ({
              relationTo: 'products';
              value: number | Product;
          } | null)
        | ({
              relationTo: 'tokens';
              value: number | Token;
          } | null)
        | ({
              relationTo: 'users';
              value: number | User;
          } | null);
    globalSlug?: string | null;
    user:
        | {
              relationTo: 'tokens';
              value: number | Token;
          }
        | {
              relationTo: 'users';
              value: number | User;
          };
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user:
        | {
              relationTo: 'tokens';
              value: number | Token;
          }
        | {
              relationTo: 'users';
              value: number | User;
          };
    key?: string | null;
    value?:
        | {
              [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaAddons_select".
 */
export interface MediaAddonsSelect<T extends boolean = true> {
    alt?: T;
    mobileAssets?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              assets400x400?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaDualPanels_select".
 */
export interface MediaDualPanelsSelect<T extends boolean = true> {
    alt?: T;
    mobileAssets?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              media950x594?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              media950x975?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              mediaSquare?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              media4x3?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGalleries_select".
 */
export interface MediaGalleriesSelect<T extends boolean = true> {
    alt?: T;
    mobileAssets?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              collage1x1?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage4x3?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage3x4?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage3x2?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              collage2x3?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaGlobals_select".
 */
export interface MediaGlobalsSelect<T extends boolean = true> {
    alt?: T;
    mobileAssets?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              bannerDesktop?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerTablet?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              storyMediaDesktop?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              storyMediaMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              mediaDividerTablet?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              mediaDividerMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaMarquees_select".
 */
export interface MediaMarqueesSelect<T extends boolean = true> {
    alt?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              marquee?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              marqueeMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mediaProducts_select".
 */
export interface MediaProductsSelect<T extends boolean = true> {
    alt?: T;
    portraitAssets?: T;
    prefix?: T;
    updatedAt?: T;
    createdAt?: T;
    url?: T;
    thumbnailURL?: T;
    filename?: T;
    mimeType?: T;
    filesize?: T;
    width?: T;
    height?: T;
    focalX?: T;
    focalY?: T;
    sizes?:
        | T
        | {
              bannerDesktop?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerTablet?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              bannerMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productPopupBanner?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productDetailBanner?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productDetailSticky?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productDetailMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productMarquee?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productMarqueeMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productListingThumbnail?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
              productListingThumbnailMobile?:
                  | T
                  | {
                        url?: T;
                        width?: T;
                        height?: T;
                        mimeType?: T;
                        filesize?: T;
                        filename?: T;
                    };
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
    slug?: T;
    entryStatus?: T;
    title?: T;
    url?: T;
    uri?: T;
    author?: T;
    testimonial?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addons_select".
 */
export interface AddonsSelect<T extends boolean = true> {
    slug?: T;
    entryStatus?: T;
    title?: T;
    url?: T;
    uri?: T;
    thumbnail?: T;
    hasNote?: T;
    note?: T;
    prices?:
        | T
        | {
              price?: T | PriceSelect<T>;
              id?: T;
          };
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Price_select".
 */
export interface PriceSelect<T extends boolean = true> {
    normalPrice?: T;
    salePrice?: T;
    isFree?: T;
    note?: T;
    additionalInfo?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    badgeTitle?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    url?: T;
    uri?: T;
    contentBlocks?: T | ContentBlocksSelect<T>;
    headerTitle?: T;
    headerDescription?: T;
    headerBackground?: T;
    category?: T;
    meta?: T | MetaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlocks_select".
 */
export interface ContentBlocksSelect<T extends boolean = true> {
    blocks?:
        | T
        | {
              callout?: T | CbCalloutSelect<T>;
              dualPanel?: T | CbDualPanelSelect<T>;
              gallery?: T | CbGallerySelect<T>;
              heading?: T | CbHeadingSelect<T>;
              marquee?: T | CbMarqueeSelect<T>;
              relatedProducts?: T | CbRelatedProductsSelect<T>;
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbCallout_select".
 */
export interface CbCalloutSelect<T extends boolean = true> {
    title?: T;
    link?: T | LinkSelect<T>;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link_select".
 */
export interface LinkSelect<T extends boolean = true> {
    source?: T;
    product?: T;
    page?: T;
    custom?: T;
    mail?: T;
    whatsappNumber?: T;
    target?: T;
    whatsappMessage?: T;
    label?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbSpacing_select".
 */
export interface CbSpacingSelect<T extends boolean = true> {
    marginTop?: T;
    marginBottom?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbDualPanel_select".
 */
export interface CbDualPanelSelect<T extends boolean = true> {
    contents?:
        | T
        | {
              type?: T;
              description?: T;
              media?: T;
              id?: T;
          };
    link?: T | LinkSelect<T>;
    layout?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbGallery_select".
 */
export interface CbGallerySelect<T extends boolean = true> {
    media?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbHeading_select".
 */
export interface CbHeadingSelect<T extends boolean = true> {
    title?: T;
    description?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbMarquee_select".
 */
export interface CbMarqueeSelect<T extends boolean = true> {
    media?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CbRelatedProducts_select".
 */
export interface CbRelatedProductsSelect<T extends boolean = true> {
    title?: T;
    products?: T;
    cbSpacing?: T | CbSpacingSelect<T>;
    id?: T;
    blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Meta_select".
 */
export interface MetaSelect<T extends boolean = true> {
    title?: T;
    description?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
    _order?: T;
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    availability?: T;
    unavailableLabel?: T;
    title?: T;
    url?: T;
    uri?: T;
    thumbnail?: T;
    thumbnailHover?: T;
    marquee?: T;
    bannerTitle?: T;
    description?: T;
    category?: T;
    badge?: T;
    quantity?: T;
    flavour?: T | FlavourSelect<T>;
    prices?:
        | T
        | {
              price?: T | PriceSelect<T>;
              id?: T;
          };
    addons?: T;
    meta?: T | MetaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Flavour_select".
 */
export interface FlavourSelect<T extends boolean = true> {
    showFlavour?: T;
    freshCreamy?: T;
    custardySpongy?: T;
    tangySweet?: T;
    fruityNutty?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tokens_select".
 */
export interface TokensSelect<T extends boolean = true> {
    title?: T;
    updatedAt?: T;
    createdAt?: T;
    enableAPIKey?: T;
    apiKey?: T;
    apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
    updatedAt?: T;
    createdAt?: T;
    email?: T;
    resetPasswordToken?: T;
    resetPasswordExpiration?: T;
    salt?: T;
    hash?: T;
    loginAttempts?: T;
    lockUntil?: T;
    sessions?:
        | T
        | {
              id?: T;
              createdAt?: T;
              expiresAt?: T;
          };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
    key?: T;
    data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
    document?: T;
    globalSlug?: T;
    user?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
    user?: T;
    key?: T;
    value?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
    name?: T;
    batch?: T;
    updatedAt?: T;
    createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
    id: number;
    navigations?:
        | {
              entryStatus: 'disabled' | 'live';
              link?: Link;
              children?:
                  | {
                        entryStatus: 'disabled' | 'live';
                        link?: Link;
                        id?: string | null;
                    }[]
                  | null;
              id?: string | null;
          }[]
        | null;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
    id: number;
    typeHandle: 'sectionHomepage';
    slug: string;
    entryStatus: 'disabled' | 'live';
    title: string;
    url?: string | null;
    uri?: string | null;
    bannerMedia?:
        | {
              source?: ('products' | 'custom') | null;
              entryStatus: 'disabled' | 'live';
              tag?: (number | null) | Tag;
              textAlign?: ('left' | 'right') | null;
              bannerOverlay?: ('0' | '1' | '2' | '3' | '4' | '5') | null;
              media?: (number | null) | MediaGlobal;
              title?: string | null;
              description?: {
                  root: {
                      type: string;
                      children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                  };
                  [k: string]: unknown;
              } | null;
              link?: Link;
              product?: (number | null) | Product;
              productTarget?: boolean | null;
              id?: string | null;
          }[]
        | null;
    highlights?:
        | {
              tag: number | Tag;
              products: (number | Product)[];
              id?: string | null;
          }[]
        | null;
    storyMediaMain?: (number | null) | MediaGlobal;
    storyMediaSecondary?: (number | null) | MediaGlobal;
    storyDescription?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    testimonials?: (number | Testimonial)[] | null;
    imageDividerMedia?: (number | null) | MediaGlobal;
    orderDescription?: {
        root: {
            type: string;
            children: {
                type: any;
                version: number;
                [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
        };
        [k: string]: unknown;
    } | null;
    orderSteps?:
        | {
              title?: string | null;
              description?: {
                  root: {
                      type: string;
                      children: {
                          type: any;
                          version: number;
                          [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                  };
                  [k: string]: unknown;
              } | null;
              id?: string | null;
          }[]
        | null;
    meta?: Meta;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
    id: number;
    address?: string | null;
    addressLink?: Link;
    businessHours?: string | null;
    socialMedia?: SocialMedia;
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Icon".
 */
export interface Icon {
    source?: 'reactIcon' | null;
    reactIcon?: ('CiInstagram' | 'CiMail') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
    navigations?:
        | T
        | {
              entryStatus?: T;
              link?: T | LinkSelect<T>;
              children?:
                  | T
                  | {
                        entryStatus?: T;
                        link?: T | LinkSelect<T>;
                        id?: T;
                    };
              id?: T;
          };
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
    typeHandle?: T;
    slug?: T;
    entryStatus?: T;
    title?: T;
    url?: T;
    uri?: T;
    bannerMedia?:
        | T
        | {
              source?: T;
              entryStatus?: T;
              tag?: T;
              textAlign?: T;
              bannerOverlay?: T;
              media?: T;
              title?: T;
              description?: T;
              link?: T | LinkSelect<T>;
              product?: T;
              productTarget?: T;
              id?: T;
          };
    highlights?:
        | T
        | {
              tag?: T;
              products?: T;
              id?: T;
          };
    storyMediaMain?: T;
    storyMediaSecondary?: T;
    storyDescription?: T;
    testimonials?: T;
    imageDividerMedia?: T;
    orderDescription?: T;
    orderSteps?:
        | T
        | {
              title?: T;
              description?: T;
              id?: T;
          };
    meta?: T | MetaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
    address?: T;
    addressLink?: T | LinkSelect<T>;
    businessHours?: T;
    socialMedia?: T | SocialMediaSelect<T>;
    updatedAt?: T;
    createdAt?: T;
    globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SocialMedia_select".
 */
export interface SocialMediaSelect<T extends boolean = true> {
    icon?: T | IconSelect<T>;
    link?: T | LinkSelect<T>;
    id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Icon_select".
 */
export interface IconSelect<T extends boolean = true> {
    source?: T;
    reactIcon?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
    data?: {
        [k: string]: unknown;
    };
    width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
    [k: string]: unknown;
}

declare module 'payload' {
    export interface GeneratedTypes extends Config {}
}
